-- Mock products data for development
-- This script inserts products with NULL supplier_id to avoid foreign key issues
-- You can create suppliers through your app's registration process and update supplier_id later

INSERT INTO public.products (name, description, price, original_price, image_url, category_id, supplier_id, in_stock, stock_count, rating, review_count, specifications, features) VALUES
('Hospital Bed Standard', 'A comfortable standard hospital bed with adjustable height and rails', 1500.00, 1800.00, '/hospital-bed-medical-equipment.jpg', 'hospital-furniture-infrastructure', NULL, true, 25, 4.5, 12, '{"brand": "MediCare", "model": "HB-100", "dimensions": "200x90cm"}', ARRAY['Adjustable height', 'Side rails', 'Durable frame']),
('ICU Bed Advanced', 'Advanced ICU bed with monitoring capabilities and emergency features', 2500.00, 3000.00, '/hospital-beds-medical-equipment.jpg', 'hospital-furniture-infrastructure', NULL, true, 10, 4.8, 8, '{"brand": "MediTech", "model": "ICU-200", "weight_capacity": "200kg"}', ARRAY['Electronic controls', 'Trendelenburg position', 'Emergency CPR release']),
('Surgical Mask Box', 'Box of 50 disposable surgical masks for infection control', 25.00, 30.00, '/surgical-masks-box.jpg', 'sterilization-infection-control', NULL, true, 100, 4.2, 25, '{"brand": "SafeGuard", "quantity": 50, "type": "disposable"}', ARRAY['Breathable material', 'Fluid resistant', 'Comfortable fit']),
('N95 Respirator Pack', 'Pack of 20 N95 respirators for high-level protection', 50.00, 60.00, '/medical-ppe-masks-gloves-safety-equipment.jpg', 'sterilization-infection-control', NULL, true, 75, 4.7, 18, '{"brand": "ProShield", "quantity": 20, "certification": "N95"}', ARRAY['High filtration', 'Adjustable straps', 'Comfortable nose clip']),
('Stethoscope Professional', 'High-quality stethoscope for accurate auscultation', 120.00, 150.00, '/diagnostic-medical-tools-stethoscope.jpg', 'diagnostic-devices', NULL, true, 30, 4.6, 15, '{"brand": "MediListen", "model": "ST-300", "chestpiece": "dual-head"}', ARRAY['Dual-head chestpiece', 'Stainless steel', 'Soft ear tips']),
('Blood Pressure Monitor Digital', 'Digital blood pressure monitor with LCD display', 80.00, 100.00, '/blood-pressure-monitor.png', 'diagnostic-devices', NULL, true, 40, 4.4, 22, '{"brand": "HealthCheck", "model": "BP-500", "cuff_size": "standard"}', ARRAY['Automatic inflation', 'Memory function', 'Large display']),
('Surgical Scissors Set', 'Set of precision surgical scissors for various procedures', 200.00, 250.00, '/surgical-instruments-medical-tools.jpg', 'therapeutic-surgical-devices', NULL, true, 15, 4.9, 7, '{"brand": "Precision", "material": "stainless steel", "set_size": 5}', ARRAY['Sharp blades', 'Ergonomic handles', 'Sterilizable']),
('Forceps Medical', 'Medical forceps for grasping and holding tissues', 150.00, 180.00, '/surgical-instruments-medical-tools.jpg', 'therapeutic-surgical-devices', NULL, true, 20, 4.3, 10, '{"brand": "MediGrip", "type": "artery forceps", "length": "15cm"}', ARRAY['Fine tips', 'Locking mechanism', 'Durable construction']),
('Laboratory Centrifuge', 'High-speed centrifuge for sample separation', 800.00, 1000.00, '/laboratory-centrifuge.jpg', 'laboratory-equipment', NULL, true, 5, 4.7, 9, '{"brand": "LabSpin", "model": "LC-1000", "max_speed": "5000rpm"}', ARRAY['Variable speed', 'Safety lid', 'Quiet operation']),
('Microscope Compound', 'Compound microscope for detailed specimen examination', 600.00, 750.00, '/laboratory-equipment-microscope-medical.jpg', 'laboratory-equipment', NULL, true, 8, 4.5, 12, '{"brand": "MicroView", "magnification": "1000x", "illumination": "LED"}', ARRAY['Binocular eyepieces', 'Mechanical stage', 'Abbe condenser']),
('Syringes Pack', 'Pack of 100 disposable syringes with needles', 30.00, 35.00, '/medical-consumables-syringes-supplies.jpg', 'disposables-consumables', NULL, true, 200, 4.1, 30, '{"brand": "MediInject", "size": "5ml", "quantity": 100}', ARRAY['Sterile', 'Sharp needles', 'Easy disposal']),
('Bandages Roll', 'Medical bandages roll for wound dressing', 15.00, 20.00, '/medical-consumables-syringes-bandages.jpg', 'disposables-consumables', NULL, true, 150, 4.0, 20, '{"brand": "CareWrap", "width": "5cm", "length": "5m"}', ARRAY['Adhesive', 'Breathable', 'Flexible']),
('Wheelchair Manual', 'Lightweight manual wheelchair for mobility assistance', 300.00, 350.00, '/wheelchair-mobility-aids-medical.jpg', 'rehabilitation-assistive', NULL, true, 12, 4.6, 14, '{"brand": "MobilityPlus", "weight": "15kg", "seat_width": "45cm"}', ARRAY['Foldable', 'Adjustable seat', 'Durable wheels']),
('Walker Adjustable', 'Adjustable walker with wheels for stability', 120.00, 140.00, '/wheelchair-mobility-aids-medical.jpg', 'rehabilitation-assistive', NULL, true, 18, 4.2, 16, '{"brand": "SteadyStep", "height_range": "80-100cm", "wheels": "4"}', ARRAY['Height adjustable', 'Locking brakes', 'Lightweight']),
('Patient Monitor Basic', 'Basic patient monitor for vital signs tracking', 500.00, 600.00, '/patient-monitor-medical.jpg', 'life-support-critical-care', NULL, true, 7, 4.8, 11, '{"brand": "VitalWatch", "parameters": "BP, HR, SpO2", "display": "LCD"}', ARRAY['Real-time monitoring', 'Alarm system', 'Portable']),
('ECG Machine Portable', 'Portable ECG machine for cardiac monitoring', 1200.00, 1500.00, '/patient-monitor-medical-vital-signs.jpg', 'life-support-critical-care', NULL, true, 4, 4.9, 6, '{"brand": "HeartScan", "leads": 12, "battery_life": "8hrs"}', ARRAY['Wireless', 'Touch screen', 'Data storage']),
('Ultrasound Gel Bottle', 'Bottle of ultrasound gel for imaging procedures', 20.00, 25.00, '/ultrasound-gel-bottle.jpg', 'disposables-consumables', NULL, true, 80, 4.3, 19, '{"brand": "EchoGel", "volume": "250ml", "type": "water-based"}', ARRAY['Non-greasy', 'Hypoallergenic', 'Long-lasting']),
('Gloves Examination Box', 'Box of 100 examination gloves for protection', 40.00, 50.00, '/medical-ppe-masks-gloves-safety-equipment.jpg', 'sterilization-infection-control', NULL, true, 90, 4.4, 23, '{"brand": "SafeHands", "size": "medium", "quantity": 100}', ARRAY['Latex-free', 'Powder-free', 'Textured grip']),
('Thermometer Digital', 'Digital thermometer for accurate temperature measurement', 25.00, 30.00, '/diagnostic-medical-tools-stethoscope.jpg', 'diagnostic-devices', NULL, true, 50, 4.1, 28, '{"brand": "TempCheck", "type": "infrared", "accuracy": "0.1°C"}', ARRAY['Fast reading', 'Memory recall', 'Fever alarm']),
('Oxygen Concentrator', 'Portable oxygen concentrator for respiratory support', 800.00, 1000.00, '/patient-monitor-medical.jpg', 'life-support-critical-care', NULL, false, 0, 4.7, 9, '{"brand": "OxyLife", "flow_rate": "5L/min", "weight": "5kg"}', ARRAY['Battery operated', 'Quiet', 'Continuous flow']);
